package enumeration;

public enum Direction {

    NORTH(0)
            {
                @Override
                public void move() {
                    System.out.println("move towards north");
                }
            },
    SOUTH(90)
            {
                @Override
                public void move() {
                    System.out.println("move towards south");
                }
            },
    EAST(180)
            {
                @Override
                public void move() {
                    System.out.println("move towards east");
                }
            },
    WEST(270)
            {
                @Override
                public void move() {
                    System.out.println("move towards west");
                }
            };

    private int degree;
    Direction(int degree)
    {
        this.degree = degree;
    }

    abstract public void move();
}


//GENERATED BY COMPILER

//public class Direction extends Enum<Direction>
//{
//    private static Direction NORTH = new Direction(0){
//        @Override
//        public void move() {
//            System.out.println("move towards north");
//        }
//    };
//    private static Direction SOUTH = new Direction(90){
//        @Override
//        public void move() {
//            System.out.println("move towards south");
//        }
//    };
//    private static Direction EAST = new Direction(180){
//        @Override
//        public void move() {
//            System.out.println("move towards east");
//        }
//    };
//    private static Direction WEST = new Direction(270){
//        @Override
//        public void move() {
//            System.out.println("move towards west");
//        }
//    };
//
//    private int degree;
//    private Direction(int degree)
//    {
//        this.degree = degree;
//    }
//
//    abstract public void move();
//}
